### ISSUE TITLE
custom product template with only categories_name fails

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/dbio#144]
Created a product template with just categories_name added to the model and ID fields. When I create then export the file only the model and ID are present. There is a header for categories_name but all cells are blank. Tested on vanilla 1.5.5f and 1.5.6 with latest dbio from this repo.

**Comment by lankeeyankee** [comment]
update: if I add one more field then the categories are added to the sheet. I can have quantity as the only additional field and it works. So it seems like the code doesn't like the category as the only addition.

**Comment by lat9** [comment]
Yes, it appears to be an issue when _only_ the special fields (e.g. categories-list or manufacturers_name) are requested.
