### ISSUE TITLE
Feature Request: Products handler allow selection of parent category

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/dbio#145]
Currently, if using the checkbox to select products within a certain category, it will not allow parent categories to be selected since it holds no products, only subcats.  It would be very useful to allow this so full category trees can be manipulated.

**Comment by lat9** [comment]
The categories' dropdown allows for multiple categories to be selected via Ctrl+Click.  I don't see the need for the additional complexity of determining sub-categories based on an upper-category selection.
