### ISSUE TITLE
Hide Import Check Report popup link title

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#161]
![Clipboard01](https://user-images.githubusercontent.com/4391026/74111086-2d90e380-4b92-11ea-893c-7bf97c2251a0.gif)

**Comment by lat9** [comment]
That's actually the `title` of the link that you clicked to get to that Colorbox popup.  I'll see what I can do via jQuery on that click to modify that text so that it's not so clumsy.

![image](https://user-images.githubusercontent.com/2685585/74149466-ce54c280-4bd5-11ea-8ad6-e3b1d398e568.png)

**Comment by torvista** [comment]
...ah, there was a clue in the html source, since it was in the title tag! While "Don't make me think" is the mantra in fashion, I often think it is needed due to user inability to carry out said requirement.

**Comment by lat9** [comment]
I'll simply update the colorbox.css to `display: none;` on that unwanted `title`.
