### ISSUE TITLE
pages folder is part of fileset/to be uploaded?

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#168]
While the docs folder may be copied in to the corresponding docs folder of ZC, this is not so clear...I assume its only Github text.
![Clipboard01](https://user-images.githubusercontent.com/4391026/83943699-7f730e80-a7fe-11ea-9d68-fa1425bc29e7.gif)

Maybe the files for upload should be in their own subdirectory as these would be for comparison with the shop files.

**Comment by lat9** [comment]
That `pages` directory (and associated files) aren't included when a DbIo release-zipfile is created; they're intended to be online-only so that documentation updates can be posted without an overall release of the plugin.

... or, perhaps I'm not understanding the issue.

**Comment by torvista** [comment]
I'm not understanding the issue.
