### ISSUE TITLE
Encoding: deprecated debugs curly brackets

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#169]
php 7.4.5

Admin
Request URI: /tienda/admin/dbio_manager.php
IP address: 127.0.0.1
#1 require() called at [...tienda/admin/includes/classes/dbio/DbIoHandler.php:97]
#2 DbIoHandler->__construct() called at [...tienda/admin/includes/classes/dbio/DbIo.php:117]
#3 DbIo->initializeConfig() called at [...tienda/admin/includes/classes/dbio/DbIo.php:37]
#4 DbIo->__construct() called at [...tienda/admin/dbio_manager.php:614]
--> PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\tienda\admin\includes\classes\dbio\Encoding.php on line 197.

Admin
Request URI: /tienda/admin/dbio_manager.php
IP address: 127.0.0.1
#1 require() called at [...tienda/admin/includes/classes/dbio/DbIoHandler.php:97]
#2 DbIoHandler->__construct() called at [...tienda/admin/includes/classes/dbio/DbIo.php:117]
#3 DbIo->initializeConfig() called at [...tienda/admin/includes/classes/dbio/DbIo.php:37]
#4 DbIo->__construct() called at [...tienda/admin/dbio_manager.php:614]
--> PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\tienda\admin\includes\classes\dbio\Encoding.php on line 199.

Admin
Request URI: /tienda/admin/dbio_manager.php
IP address: 127.0.0.1
#1 require() called at [...tienda/admin/includes/classes/dbio/DbIoHandler.php:97]
#2 DbIoHandler->__construct() called at [...tienda/admin/includes/classes/dbio/DbIo.php:117]
#3 DbIo->initializeConfig() called at [...tienda/admin/includes/classes/dbio/DbIo.php:37]
#4 DbIo->__construct() called at [...tienda/admin/dbio_manager.php:614]
--> PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\tienda\admin\includes\classes\dbio\Encoding.php on line 200.

Admin
Request URI: /tienda/admin/dbio_manager.php
IP address: 127.0.0.1
#1 require() called at [...tienda/admin/includes/classes/dbio/DbIoHandler.php:97]
#2 DbIoHandler->__construct() called at [...tienda/admin/includes/classes/dbio/DbIo.php:117]
#3 DbIo->initializeConfig() called at [...tienda/admin/includes/classes/dbio/DbIo.php:37]
#4 DbIo->__construct() called at [...tienda/admin/dbio_manager.php:614]
--> PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\tienda\admin\includes\classes\dbio\Encoding.php on line 201.

**Comment by lat9** [comment]
Thanks, @torvista, for the report and correction!
