### ISSUE TITLE
Product Import-Update clarification

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#173]
> Starting with DbIo v1.1.0, a product's record can be located via either its products_id or products_model (both columns are required in the import file)

For an update of product data, I am investigating some errors and am unclear on the process.

If a product can be located by either field and both are  required columns, how do I force it to use the id, to ignore/overwrite the model?

**Comment by lat9** [comment]
The `id` is overriding.  For instance, I changed a demo-product's model number (and quantity) via this `dbio.Products.test.csv`
```
v_products_id,v_products_model,v_products_quantity,v_dbio_command
1,MG200MMS-updated,18,
```
