### ISSUE TITLE
IDE inspection DbIoHandler.php, protected access queries

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#188]
phpStorm is flagging this as a bug on queries

ADMIN\includes\classes\dbio\DbIoHandler.php
![Clipboard01](https://user-images.githubusercontent.com/4391026/113477356-8223ac00-9481-11eb-9ccf-24ee84a91df5.gif)

I'm not sure if it is.

**Comment by lat9** [comment]
I'm thinking that it's a false positive.  The `includes/classes/query_class.php` has only public methods and no declarations of protected status on the queries array.

In addition, the DbIoHandler's `queryCache` and `queryCacheOlder` variables are created in the public __construct method, thus making them also public.

**Comment by torvista** [comment]
Ah, a minor but significant bit of information would be that this in is ZC158!!. Sorry!
```
class QueryCache
{
    protected $queries = [];

    /**
     * Cache SELECT statement query resources in application memory
     * returns TRUE if and only if query has been stored in cache
     * @param string $query query string, used as a key
     * @param mysqli_result $valueToStore result from mysqli_query
     * @return bool
     */
```

**Comment by lat9** [comment]
Still a phantom.  The `queries` element of the QueryCache class is directly accessed only for the older (ca. zc151) version of the `query_class.php` class.

**Comment by torvista** [comment]
After forcing myself to understand this, you are of course, right.

**Comment by torvista** [comment]
From what I see, this "offending" bit of code is for an older query_class object that did not have the "reset" method: this was introduced in ZC153.
