### ISSUE TITLE
php warning when no match for category on add/insert a new product

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#191]
php 8.0.8, strict errors

> The following warnings/errors were generated by the above action:
> ✗ Product not inserted at line number 2, no match found for categories_name (Fabricantes).

> [16-Jul-2021 18:03:42 Europe/Madrid] Request URI: /zencart-158/admin/index.php?cmd=dbio_manager&action=file, IP address: 127.0.0.1
> #1  DbIoProductsHandler->importAddField() called at [...\zencart-158\admin\includes\classes\dbio\DbIoHandler.php:1410]
> #2  DbIoHandler->importProcessField() called at [...\zencart-158\admin\includes\classes\dbio\DbIoHandler.php:894]
> #3  DbIoHandler->importCsvRecord() called at [...\zencart-158\admin\includes\classes\dbio\DbIo.php:265]
> #4  DbIo->dbioImport() called at [...\zencart-158\admin\dbio_manager.php:240]
> #5  require(...\zencart-158\admin\dbio_manager.php) called at [...\zencart-158\admin\index.php:11]
> --> PHP Warning: Undefined variable $manufacturers_id in ...\zencart-158\admin\includes\classes\dbio\DbIoProductsHandler.php on line 972.

**Comment by lat9** [comment]
I'm thinking that the data-import record for this issue has more than just a missing categories_name. 
-  Was there a non-empty manufacturer name indicated?  
-  Was that manufacturer_name present in the database?
- Was the error logged during an actual import or just a 'check' operation?

**Comment by torvista** [comment]
Sorry, I forgot about this and didn't make good enough notes....I've tried the files that were being worked with on that day but can't reproduce the fault. So closing for now.

**Comment by lat9** [comment]
FWIW, those questions were based on a corner-case that I found when reviewing the DbIoProducts.php module; I'll have a correction real-soon-now.
