### ISSUE TITLE
DBIoHandler using protected variable from query_cache

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#200]
IDE flags as a real error (as opposed to a warning):

https://github.com/lat9/dbio/blob/0579df4954f56ff5ba453b7ac9e42342b5674e0e/YOUR_ADMIN/includes/classes/dbio/DbIoHandler.php#L801

https://github.com/zencart/zencart/blob/6de01e2e6ce1b5d895743d9421bac6b52ae79957/includes/classes/query_cache.php#L16

I've not seen any error in real use.

**Comment by lat9** [comment]
That's because that/those clauses aren't executed unless the associated class exists.
