### ISSUE TITLE
php 8.2: explicitly declaring variables

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#201]
I've done the necessary for products so far, making all variables protected until an error demands public.

**Comment by lat9** [comment]
I'm pretty sure (i.e. not 100%) that all the DbIo admin tools make use solely of the DbIo handlers' public methods to 'do their thing'.  As you indicated, `protected` is preferred unless there's some compatibility issue that would require making a variable `public`.

**Comment by torvista** [comment]
I've only used products and OptionsStock handlers.
For those I put the definitions as demanded by the debug logs. A few need to be public.
I've done a branch in my fork with these changes, and one fix for an unrelated debug
