### ISSUE TITLE
unable to resize select windows in Safari

### ISSUE THREAD

**Issue by torvista** [lat9/dbio#205]
![Clipboard01](https://user-images.githubusercontent.com/4391026/202473148-92c3ad2d-fa50-4ed5-baa7-00ae33ec626a.gif)
These select boxes have css resize: horizontal. I changed that that to both which is ok for windows.
But on Safari there is no resize at all.
https://stackoverflow.com/questions/13252835/safari-change-select-height
suggests 
-webkit-appearance: none;
which did not work.
I don't have access to a mac to investigate further, this was pointed out by a remote-working employee.

**Comment by lat9** [comment]
Sigh, Safari.  I don't have access to a Mac either; I'll check with others to see if I can find someone to collaborate with to find a solution

**Comment by torvista** [comment]
If not, I can get him to bring a mac laptop into the office next week.

**Comment by lat9** [comment]
Just found [this](https://stackoverflow.com/questions/34660500/mobile-safari-multi-select-bug) stackoverflow posting; I'll see how that works.

**Comment by lat9** [comment]
If anyone's got an Apple device that can test that this works, it would be a great help!

**Comment by torvista** [comment]
Still not working: I'll have an Macbook available tomorrow to try more options.

**Comment by lat9** [comment]
Those multiple-selects use `resize: vertical;`, just as an aside.

If you've got access to a Mac, does the resizing work on this demo page: https://developer.mozilla.org/en-US/docs/Web/CSS/resize

**Comment by torvista** [comment]
Luismi says these all work in Safari/Mac.

**Comment by lat9** [comment]
I think the just-pushed change might nail the issue.  I was after-the-fact (via jQuery) setting the `resize: vertical;` CSS property.  I've now moved that to the `<style>` element in the `<head>`.  I'm hopeful (??) that that change will be the solution; let me know as this is the last bit before the release.

**Comment by torvista** [comment]
On the Mozilla web demo, there is the bottom-corner-resize tab and all the examples work, but the tab is not on DBIO

![Captura de Pantalla 2023-01-16 a las 14 09 53](https://user-images.githubusercontent.com/4391026/212705873-0520918a-75b3-492a-8229-255516ecf1fe.png)

**Comment by torvista** [comment]
After stripping out all css I got them to be resizeable.

`select[multiple] { resize:both;overflow:auto;padding:1px }`
works but padding in
`select { padding: 0.1em; margin: 0.5em; }`
breaks it. And yes it does need all three selectors.
But unfortunately the equivalent of "do not cache" in Developer tools in Safari does not work, so that's two hours lost battling with maybe-maybe-not caching hell.
Even using a separate css file and dbio.css?timestamp did not prevent it caching. What a piece of crap.
I'll have another go on Thursday, then let the mac users sort it out, if there are any.

**Comment by lat9** [comment]
@torvista, I've got that updated in both the admin tools, noting that using `resize: both` can throw the alignment off so I chose to continue to use `resize: vertical`.
