### ISSUE TITLE
Enable use on Zen Cart versions prior to 1.5.0

### ISSUE THREAD

**Issue by lat9** [lat9/dbio#54]
Add the dhtml files to enable the use of DbIo on pre-Zen Cart v1.5.0 installations.

**Comment by drbyte** [comment]
Does it make sense to remove this file nowadays?

**Comment by lat9** [comment]
I dunno.  We're still seeing a bunch of zc139/zc138 sites coming to upgrade.

**Comment by drbyte** [comment]
Fair. I wasn't thinking that they'd be as likely to be installing this package.

I have no strong opinion. I just noticed the file in the zip and it stood out :)
